### ISSUE TITLE
Invalid requestId value

### ISSUE THREAD

**Issue by Alvaro-Serquo** [KAL-ATM-Software/KAL_XFS4IoT_SP-Dev-Samples#2]
Based on the documentation:

> "**requestId**", int : Unique request identifier supplied by the client used to correlate the command with acknowledge, event and completion messages. For unsolicited messages the value will be zero. For all other message types this will be an integer. The client will supply values that are positive, incremental and start with 1, so that unsolicited events can be distinguished. The service will check that the requestID does not conflict with a currently executing or queued command request from the same client and reject if it does.

requestId in a command should be different than 0 and the Common.GetServices command sends a requestId=0

**Comment by seishinakano** [comment]
Thanks Alvaro,
It was known issue within KAL and we addressed requestId starting from 1 in the next updates of sample code for supporting CashDispenser framework and test tools.
New release for the CashDispenser sample and test program is published on the 6th of July. therefore, we will close this issue.
