### ISSUE TITLE
vendorName not lowerCamel

### ISSUE THREAD

**Issue by Alvaro-Serquo** [KAL-ATM-Software/KAL_XFS4IoT_SP-Dev-Samples#3]
The discovery command returns field vendorname instead of vendorName

**Comment by seishinakano** [comment]
Thanks Alvaro,
You are right on this and the name of property 'vendorname' should be camelCase 'vendorName'. We need to change YAML for the API document as the KAL tool is generating an internal structure for the messages programatically.
KAL raised a pull request 'API: Minor update/correction for the ServiceDiscovery #196' in the XFS GitHub. 
Once it's resolved, we can update KAL SP framework to use correct property name. 
Keep this issue opened until it's solved in the SP framework repository.

**Comment by seishinakano** [comment]
Hi Alvaro,
We are planning to add fix in the next package v0.0.2-alpha.2 including TextTerminal SP framework.
It will be published before next workshop planned on the 3rd August.

**Comment by seishinakano** [comment]
New package v0.0.2-alpha.2 addresses this issue.
